# Generated by Django 3.2 on 2022-09-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('item', 'profile')},
        ),
    ]
